### ISSUE TITLE
Mod searching does not work

### ISSUE THREAD

**Issue by ExoPlant** [ExoPlant/packwiz-gui#26]

**Comment by Samisafool** [comment]
I can suggest something: `sg.Output()` works but is jank and requires it to be a non-blocking window open seperately. pain

**Comment by ExoPlant** [comment]
I have an idea but it may only work reliably on Windows

**Comment by Samisafool** [comment]
Throw it at me

**Comment by ExoPlant** [comment]
Opening a command window with the packwiz command in it

**Comment by ExoPlant** [comment]
Oop wrong button

**Comment by Samisafool** [comment]
LOL

People would freak out if search didn't trigger

**Comment by Samisafool** [comment]
Oh wait, we could also do `xdg-terminal` on Linux

**Comment by Samisafool** [comment]
It's kinda trashy tho

**Comment by ExoPlant** [comment]
Okay, we can try that

**Comment by Samisafool** [comment]
No we can NOT

please don't

**Comment by ExoPlant** [comment]
Why not?

**Comment by Samisafool** [comment]
Bruh

Do I need to explain the fact that:

1. It doesn't work on mac
2. It doesn't work on *BSD
3. People will freak out at a terminal opening and closing if there is no search
4. It won't output to stdout which is bad for logging purposes
5. It's janky

**Comment by ExoPlant** [comment]
Fixed in b5033afe452bb0cc7bfd07fd62b106d7fb87b849
