### ISSUE TITLE
TODO: Fix placements

### ISSUE THREAD

**Issue by ExoPlant** [ExoPlant/packwiz-gui#34]
See packwizgui.kv line 9 https://github.com/ExoPlant/packwiz-gui/blob/6c693e02af3bb52da2aad4ca7236a6df703e117d/packwizgui.kv#L9

**Comment by ExoPlant** [comment]
Current placement: 
![image](https://user-images.githubusercontent.com/49562894/147857866-54b0740f-0bf2-43b1-b463-b773cc611533.png)

**Comment by ExoPlant** [comment]
Someone fix this

**Comment by Samisafool** [comment]
Can I close this???

**Comment by ExoPlant** [comment]
Fixed in 
3535b46
