### ISSUE TITLE
Need ability to edit existing packs

### ISSUE THREAD

**Issue by Samisafool** [ExoPlant/packwiz-gui#4]
Maybe a button that allows you to choose an existing one, opens a window and imports all the settings in, allows adding more mods etc

**Comment by ExoPlant** [comment]
Working on this next 👍

**Comment by Samisafool** [comment]
Why would you close it if you're working on it smh

**Comment by ExoPlant** [comment]
Good point

**Comment by ExoPlant** [comment]
Now done in c568393594f463c7513ab38d74e157a0c4069193
