### ISSUE TITLE
Imported packs don't work, because there's no author key in the pack.toml

### ISSUE THREAD

**Issue by Samisafool** [ExoPlant/packwiz-gui#57]

**Comment by ExoPlant** [comment]
Is this packwiz's fault or ours?

**Comment by Samisafool** [comment]
Both, because we should not crash on no author key, but it should also have an author key

**Comment by Samisafool** [comment]
I'll fix it and add some more crash handling in the process

**Comment by ExoPlant** [comment]
So if packwiz fixes it then it's mainly fixed on our end? Can you pester @comp500 to auto set it to 'Unknown' or something

**Comment by Samisafool** [comment]
BRUH

Why would you ping

and why is it necessary to fix it on packwiz's end?

**Comment by comp500** [comment]
I don't mind being pinged :) but I will note that the author field is optional, see https://packwiz.infra.link/reference/pack-format/pack-toml/. Do make an issue on the packwiz repo about importing the pack author/version though, that'd be nice to have.

**Comment by Samisafool** [comment]
Yeah well I fixed the author thing in #58, and I'll make an issue when I get home (heading out rn)

**Comment by Samisafool** [comment]
aaaand I've opened up packwiz/packwiz#83, and I think I should open one about `modrinth import` too.
